# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=terraform', '--tag=gcr.io/$PROJECT_ID/terraform', '-f', 'Dockerfile', '.']

# Simple sanity check: invoke the new gcloud container to confirm that it was
# built correctly.
- name: 'gcr.io/$PROJECT_ID/terraform'
  args: ['version']

images:
- 'gcr.io/$PROJECT_ID/terraform'

timeout: 1200s